spring:
  application:
    name: digital-banking-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/digital_banking_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.kavya.digitalbanking: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE